imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%databasetest.host%"
        dbname:   "%databasetest.dbname%"
        user:     "%databasetest.user%"
        password: "%databasetest.password%"

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
