<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * QuotationRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuotationRequestRepository extends EntityRepository
{
    public function findDashboardMetrics()
    {
        $qb = $this->createQueryBuilder('qr');
        $qb->select('COUNT(qr) as nb, qr.status')->groupBy('qr.status');
        return $qb->getQuery()->execute();
    }

    public function findAllGeoLocated() {
        $qb = $this->createQueryBuilder('qr');
        $qb->where("qr.point is not null");
        $results = $qb->getQuery()->execute();

        var_dump(count($results));
        return $results;

    }
}
