<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * QuotationRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuotationRequestRepository extends EntityRepository
{
    public function findDashboardMetrics()
    {
        $qb = $this->createQueryBuilder('qr');
        $qb->select('COUNT(qr) as nb, qr.status')->groupBy('qr.status');
        return $qb->getQuery()->execute();
    }
}
